In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import joblib

In [2]:
df = pd.read_csv("data\CropYield\yield_df.csv")

df.head()

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

In [3]:
print("Shape :", df.shape)

print("\nColumns")

print(df.columns)

print("\nMissing Values")

print(df.isnull().sum())

Shape : (28242, 8)

Columns
Index(['Unnamed: 0', 'Area', 'Item', 'Year', 'hg/ha_yield',
       'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp'],
      dtype='object')

Missing Values
Unnamed: 0                       0
Area                             0
Item                             0
Year                             0
hg/ha_yield                      0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
dtype: int64

In [4]:
# Remove index column
df.drop("Unnamed: 0", axis=1, inplace=True)

# Verify
print(df.head())
print("\nShape :", df.shape)

      Area         Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  \
0  Albania        Maize  1990        36613                         1485.0
1  Albania     Potatoes  1990        66667                         1485.0
2  Albania  Rice, paddy  1990        23333                         1485.0
3  Albania      Sorghum  1990        12500                         1485.0
4  Albania     Soybeans  1990         7000                         1485.0

   pesticides_tonnes  avg_temp
0              121.0     16.37
1              121.0     16.37
2              121.0     16.37
3              121.0     16.37
4              121.0     16.37

Shape : (28242, 7)

In [5]:
from sklearn.preprocessing import LabelEncoder

# Create encoders
area_encoder = LabelEncoder()
item_encoder = LabelEncoder()

# Encode categorical columns
df["Area"] = area_encoder.fit_transform(df["Area"])
df["Item"] = item_encoder.fit_transform(df["Item"])

print(df.head())

   Area  Item  Year  hg/ha_yield  average_rain_fall_mm_per_year  \
0     0     1  1990        36613                         1485.0
1     0     3  1990        66667                         1485.0
2     0     4  1990        23333                         1485.0
3     0     5  1990        12500                         1485.0
4     0     6  1990         7000                         1485.0

   pesticides_tonnes  avg_temp
0              121.0     16.37
1              121.0     16.37
2              121.0     16.37
3              121.0     16.37
4              121.0     16.37

In [6]:
print(df.dtypes)

Area                               int64
Item                               int64
Year                               int64
hg/ha_yield                        int64
average_rain_fall_mm_per_year    float64
pesticides_tonnes                float64
avg_temp                         float64
dtype: object

In [7]:
import joblib

joblib.dump(area_encoder, "area_encoder.pkl")
joblib.dump(item_encoder, "item_encoder.pkl")

print("Encoders Saved Successfully")

Encoders Saved Successfully

In [8]:
# Features
X = df.drop("hg/ha_yield", axis=1)

# Target
y = df["hg/ha_yield"]

print("Feature Shape :", X.shape)
print("Target Shape :", y.shape)

print("\nFeatures:")
print(X.columns)

Feature Shape : (28242, 6)
Target Shape : (28242,)

Features:
Index(['Area', 'Item', 'Year', 'average_rain_fall_mm_per_year',
       'pesticides_tonnes', 'avg_temp'],
      dtype='object')

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Features :", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Target :", y_train.shape)
print("Testing Target :", y_test.shape)

Training Features : (22593, 6)
Testing Features : (5649, 6)
Training Target : (22593,)
Testing Target : (5649,)

In [10]:
print(X_train.head())

       Area  Item  Year  average_rain_fall_mm_per_year  pesticides_tonnes  \
5493     18     5  2005                         1604.0             829.59
10969    42     6  1992                         1083.0           70791.00
2001      8     0  1997                         1292.0             484.59
22157    73     3  1997                          494.0           16936.00
311       2     7  2005                         1010.0              40.00

       avg_temp
5493      25.36
10969     25.91
2001      25.81
22157     23.76
311       24.41

In [11]:
from sklearn.linear_model import LinearRegression

# Create model
lr_model = LinearRegression()

# Train model
lr_model.fit(X_train, y_train)

print("Linear Regression Model Trained Successfully")

Linear Regression Model Trained Successfully

In [12]:
lr_pred = lr_model.predict(X_test)

In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

lr_mae = mean_absolute_error(y_test, lr_pred)
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_pred))
lr_r2 = r2_score(y_test, lr_pred)

print("Linear Regression Performance")
print("-"*35)

print("MAE :", lr_mae)
print("RMSE:", lr_rmse)
print("R2 Score:", lr_r2)

Linear Regression Performance
-----------------------------------
MAE : 62444.31062975583
RMSE: 81501.76446544641
R2 Score: 0.08425172276039417

In [14]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=42)

dt_model.fit(X_train, y_train)

print("Decision Tree Model Trained Successfully")

Decision Tree Model Trained Successfully

In [15]:
dt_pred = dt_model.predict(X_test)

In [16]:
dt_mae = mean_absolute_error(y_test, dt_pred)
dt_rmse = np.sqrt(mean_squared_error(y_test, dt_pred))
dt_r2 = r2_score(y_test, dt_pred)

print("Decision Tree Performance")
print("-"*35)

print("MAE :", dt_mae)
print("RMSE:", dt_rmse)
print("R2 Score:", dt_r2)

Decision Tree Performance
-----------------------------------
MAE : 4103.842627013631
RMSE: 13498.73499660563
R2 Score: 0.9748795027896955

In [17]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("Random Forest Model Trained Successfully")

Random Forest Model Trained Successfully

In [18]:
rf_pred = rf_model.predict(X_test)

In [19]:
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest Performance")
print("-"*35)

print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R2 Score:", rf_r2)

Random Forest Performance
-----------------------------------
MAE : 3741.5348946716235
RMSE: 10190.30492818692
R2 Score: 0.9856841727959965

In [20]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "MAE": [
        lr_mae,
        dt_mae,
        rf_mae
    ],
    "RMSE": [
        lr_rmse,
        dt_rmse,
        rf_rmse
    ],
    "R2 Score": [
        lr_r2,
        dt_r2,
        rf_r2
    ]
})

results = results.sort_values(by="R2 Score", ascending=False)

results

               Model           MAE          RMSE  R2 Score
2      Random Forest   3741.534895  10190.304928  0.985684
1      Decision Tree   4103.842627  13498.734997  0.974880
0  Linear Regression  62444.310630  81501.764465  0.084252

In [21]:
import joblib

joblib.dump(rf_model, "yield_prediction_model.pkl")

print("Model Saved Successfully")

Model Saved Successfully

In [22]:
loaded_model = joblib.load("yield_prediction_model.pkl")

print(type(loaded_model))

<class 'sklearn.ensemble._forest.RandomForestRegressor'>

In [23]:
sample_prediction = loaded_model.predict(X_test.iloc[:5])

print("Predictions:")
print(sample_prediction)

Predictions:
[ 71381.635  24199.735  50744.165 162747.93   58090.93 ]

## Summary

1. The crop yield dataset was preprocessed by removing unnecessary columns and encoding categorical features (Area and Item) using Label Encoding.

2. The dataset was divided into training (80%) and testing (20%) sets for model development and evaluation.

3. Three regression models—Linear Regression, Decision Tree Regressor, and Random Forest Regressor—were trained to predict crop yield.

4. Model performance was evaluated using Mean Absolute Error (MAE), Root Mean Squared Error (RMSE), and R² Score.

5. Random Forest achieved the highest prediction accuracy with the lowest error values, outperforming the other regression models.

6. The trained Random Forest model was selected as the final crop yield prediction model.

7. The final model was saved for future predictions and deployment.